### ISSUE TITLE
ViewModel closing when navigate to new page

### ISSUE THREAD

**Issue by okunevdm** [Catel/Catel#1238] opened 2018-11-27 16:35 UTC
Catel.MVVM.Xamarin.Forms
After navigate to new page previous ViewModel is closing. And when press back button and return to first page viewmodel for this page create new instance.
is catel:ContentPage contains property like CloseViewModelOnUnloaded?

### Expected behaviour

when NavigateForward ViewModel continues to work on background.
when NavigateBack ViewModel closing.

### Actual behaviour

ViewModel closing when NavigateForward

**Comment by GreenKn1ght** [comment] 2019-02-06 08:58
This is a critical bug in Xamarin.Android due to the fact that Page.OnAppearing is called every time the page appears on the phone screen: this **may** be caused by navigation or by the OS when the app/phone comes out of sleep.
CloseViewModelOnUnloaded can't help because then you will have to handle the page lifecycle on your own.

**Comment by GeertvanHorrik** [comment] 2019-02-21 12:40
We definitely want to fix this, but might need a bit of help here, interested?

**Comment by okunevdm** [comment] 2019-02-21 15:25
I fix this bug in my project by create my own ContentPage with needed behaviour of _userControlLogic

**Comment by GreenKn1ght** [comment] 2019-02-21 17:53
@okunevdm did you use the UserControlLogic.CloseViewModelOnUnloaded property or came up with another solution?

**Comment by GreenKn1ght** [comment] 2019-02-21 18:08
I solved this by overriding the [OnParentSet](https://docs.microsoft.com/ru-ru/dotnet/api/xamarin.forms.page.onparentset?view=xamarin-forms#Xamarin_Forms_Page_OnParentSet) method and firing Loaded and Unloaded events depending on whether the [Parent](https://docs.microsoft.com/ru-ru/dotnet/api/xamarin.forms.element.parent?view=xamarin-forms#Xamarin_Forms_Element_Parent) is null.
But before creating PR I need to test it at least on UWP and iOS.

**Comment by GreenKn1ght** [comment] 2019-02-21 18:15
By the way, we still want to know when the view appears or disappears in associated view model. Any thoughts? Can we extend ViewModelBase with OnAppearing and OnDisappearing methods?

**Comment by GeertvanHorrik** [comment] 2019-02-21 18:17
Why would you want Appearing / Disappearing methods, aren't they equal to Loaded/  Unloaded? In that case, you can (should) implement this in the iView implementation so Catel can deal with this.

**Comment by GreenKn1ght** [comment] 2019-02-21 18:25
> I solved this by overriding the [OnParentSet](https://docs.microsoft.com/ru-ru/dotnet/api/xamarin.forms.page.onparentset?view=xamarin-forms#Xamarin_Forms_Page_OnParentSet) method and firing Loaded and Unloaded events depending on whether the [Parent](https://docs.microsoft.com/ru-ru/dotnet/api/xamarin.forms.element.parent?view=xamarin-forms#Xamarin_Forms_Element_Parent) is null.
> But before creating PR I need to test it at least on UWP and iOS.

With this they won't longer be equal. Unloaded will be fired when our page leaves the navigation stack.

**Comment by GreenKn1ght** [comment] 2019-02-21 18:37
I'll prepare sample to show this behavior.

**Comment by okunevdm** [comment] 2019-02-21 19:55
> @okunevdm did you use the UserControlLogic.CloseViewModelOnUnloaded property or came up with another solution?

this is my ContentPage class
`    public class ContentPage : global::Xamarin.Forms.ContentPage, IView
    {
        private readonly UserControlLogic _userControlLogic;
        private object _oldbindingContext;

        public ContentPage()
            : this(null)
        {
            BindingContextChanged += OnBindingContextChanged;
        }

        private void OnBindingContextChanged(object o, EventArgs eventArgs)
        {
            DataContextChanged?.Invoke(this, new DataContextChangedEventArgs(_oldbindingContext, BindingContext));
            _oldbindingContext = BindingContext;
            RaiseViewModelChanged();
        }

        public ContentPage(IViewModel viewModel)
        {
            _userControlLogic = new UserControlLogic(this, null, viewModel);
            _userControlLogic.TargetViewPropertyChanged += (sender, e) =>
            {
                OnPropertyChanged(e.PropertyName);
            };

            _userControlLogic.ViewModelClosedAsync += OnViewModelClosedAsync;

            _userControlLogic.ViewModelChanged += (sender, args) =>
            {
                if (!ObjectHelper.AreEqual(BindingContext, _userControlLogic.ViewModel))
                {
                    BindingContext = _userControlLogic.ViewModel;
                }
            };

            _userControlLogic.ViewModelPropertyChanged += (sender, e) =>
            {
                OnViewModelPropertyChanged(e);
                ViewModelPropertyChanged?.Invoke(this, e);
            };

            Loaded += (sender, e) =>
            {
            };

            Unloaded += (sender, e) =>
            {
            };

            DataContextChanged += OnDataContextChanged;

            this.CustomBackButtonAction = OnBackButtonActionAsync;
        }

        public IViewModel ViewModel => DataContext as IViewModel;

        public event EventHandler<EventArgs> ViewModelChanged;

        public event EventHandler<PropertyChangedEventArgs> ViewModelPropertyChanged;

        public object DataContext
        {
            get => BindingContext;
            set => BindingContext = value;
        }

        public object Tag { get; set; }

        public event EventHandler<EventArgs> Loaded;

        public event EventHandler<EventArgs> Unloaded;

        public event EventHandler<DataContextChangedEventArgs> DataContextChanged;


        private void OnViewModelPropertyChanged(PropertyChangedEventArgs e)
        {
        }

        private void RaiseViewModelChanged()
        {
            OnViewModelChanged();
            ViewModelChanged?.Invoke(this, EventArgs.Empty);
        }

        protected virtual void OnViewModelChanged()
        {
        }

        protected virtual Task OnViewModelClosedAsync(object sender, ViewModelClosedEventArgs e)
        {
            return TaskHelper.Completed;
        }

        public event EventHandler<EventArgs> BackButtonPressed;

        protected override void OnAppearing()
        {
            Loaded?.Invoke(this, EventArgs.Empty);

            base.OnAppearing();
        }

        protected override void OnDisappearing()
        {
            base.OnDisappearing();

            Unloaded?.Invoke(this, EventArgs.Empty);
        }

        protected sealed override bool OnBackButtonPressed()
        {
            /*
            BackButtonPressed.SafeInvoke(this);
            var popupLayout = Content as PopupLayout;
            //// TODO: Lookup for top most popup layout.
            return popupLayout != null && popupLayout.IsPopupActive || base.OnBackButtonPressed();
            */

            BackButtonPressed?.Invoke(this, EventArgs.Empty);

            return base.OnBackButtonPressed();
        }

        private void OnDataContextChanged(object sender, DataContextChangedEventArgs eventArgs)
        {
            ViewModelChanged?.Invoke(this, EventArgs.Empty);
        }

        public Action CustomBackButtonAction { get; set; }
        protected async void OnBackButtonActionAsync()
        {
            if (await _userControlLogic.CancelAndCloseViewModelAsync())
            {
                await Navigation.PopAsync(true);
            }
        }
    }
`

**Comment by okunevdm** [comment] 2019-02-21 20:01
for hardware back button in android i override in MainActivity
`        
public override void OnBackPressed()
        {
            // retrieve the current xamarin forms page instance
            var currentPage = Xamarin.Forms.Application.Current.MainPage.Navigation.NavigationStack.LastOrDefault();
            // check if the page has subscribed to  the custom back button event
            if (currentPage != null &&
                currentPage.GetType().IsSubclassOf(typeof(DmMobile.Controls.ContentPage)) &&
                ((DmMobile.Controls.ContentPage)currentPage).CustomBackButtonAction != null)
            {
                // invoke the Custom back button action
                ((DmMobile.Controls.ContentPage)currentPage).CustomBackButtonAction.Invoke();
                // and disable the default back button action
            }
            else
            {
                base.OnBackPressed();
            }
        }
`

**Comment by GreenKn1ght** [comment] 2019-02-21 22:06
Probably I'm blind, but there is only one difference: CustomBackButtonAction. I do not see how this changes the current behavior.

**Comment by GreenKn1ght** [comment] 2019-02-21 22:25
Please take a look at my [sample](https://github.com/GreenKn1ght/Catel.Xamarin.Forms.Todo).

**Comment by okunevdm** [comment] 2019-02-22 05:13
> Probably I'm blind, but there is only one difference: CustomBackButtonAction. I do not see how this changes the current behavior.

CustomBackButtonAction uses in concrete instance of contentPage:
`
	[XamlCompilation(XamlCompilationOptions.Compile)]
	public partial class SettingsView
    {
		public SettingsView()
		{
			InitializeComponent ();

            CustomBackButtonAction = async () =>
            {
                var result = await this.DisplayAlert(Properties.Resources.Warning, Properties.Resources.ConfirmWithoutSaving, Properties.Resources.Yes, Properties.Resources.No);

                if (result)
                {
                    OnBackButtonActionAsync();
                }
            };
        }
    }
`

**Comment by okunevdm** [comment] 2019-02-22 05:17
now i can not use ViewModel for management of Navigation behavior because of issue [https://github.com/Catel/Catel/issues/1252](url)

**Comment by GreenKn1ght** [comment] 2019-02-22 06:06
Thus you prevent navigation. We should make it work out of the box, but initial issue is "After navigate to new page previous ViewModel is closing". How do fix it?

**Comment by okunevdm** [comment] 2019-02-22 06:11
default CustomBackButtonAction is `protected async void OnBackButtonActionAsync()`
in constructor: `this.CustomBackButtonAction = OnBackButtonActionAsync;`
when back button pressed (hardware or software) it call CustomBackButtonAction. and then:

```
    protected async void OnBackButtonActionAsync()
    {
        if (await _userControlLogic.CancelAndCloseViewModelAsync())
        {
            await Navigation.PopAsync(true);
        }
    }

```

**Comment by GreenKn1ght** [comment] 2019-02-22 06:14
But if you navigate forward, your view model will still be closed and then recreated.

**Comment by okunevdm** [comment] 2019-02-22 06:22
oh, yes of course.. )) I forgot that I really used CloseViewModelOnUnloaded and when copy paste code of ContentPage i cut it... sorry.
I add this property to ContentPage and set it to false:

```
    public class ContentPage : global::Xamarin.Forms.ContentPage, IView
    {
     ...
        public ContentPage(IViewModel viewModel)
        {
            ....
            _userControlLogic = new UserControlLogic(this, null, viewModel);
            CloseViewModelOnUnloaded = false;
           ....
        }
        public bool CloseViewModelOnUnloaded
        {
            get { return (bool)GetValue(CloseViewModelOnUnloadedProperty); }
            set { SetValue(CloseViewModelOnUnloadedProperty, value); _userControlLogic.CloseViewModelOnUnloaded = CloseViewModelOnUnloaded; }
        }
        public static readonly BindableProperty CloseViewModelOnUnloadedProperty = BindableProperty.Create(nameof(CloseViewModelOnUnloaded), typeof(bool), typeof(ContentPage), false);
    }

```

**Comment by GreenKn1ght** [comment] 2019-02-22 06:33
Now it makes sense!
But you should be wary of navigating backwards using the NavigationPage and NavigationService.

**Comment by okunevdm** [comment] 2019-02-22 06:35
why? i use NavigationPage and it work fine.

**Comment by GreenKn1ght** [comment] 2019-02-22 06:38
Because in this way the view model will not be closed.

**Comment by okunevdm** [comment] 2019-02-22 06:43
it closed via 
```
        protected sealed override bool OnBackButtonPressed()
        {
            BackButtonPressed?.Invoke(this, EventArgs.Empty);
            return base.OnBackButtonPressed();
        }
```
and then `OnBackPressed()` in MainActivity
in my project VM closing. may be i forgot something again?... )

**Comment by GreenKn1ght** [comment] 2019-02-22 06:47
As you said, this will be called 

> when back button pressed (hardware or software).

But NavigationPage and NavigationService aren't buttons :)

**Comment by okunevdm** [comment] 2019-02-22 07:00
Yes, you are right! I use CustomNavigationPageRenderer in Android.
```
[assembly: ExportRenderer(typeof(NavigationPage), typeof(DmMobile.Droid.Renderers.CustomNavigationPageRenderer))]
namespace DmMobile.Droid.Renderers
{
    public class CustomNavigationPageRenderer : NavigationPageRenderer, IOnClickListener
    {
        public CustomNavigationPageRenderer(Android.Content.Context context) : base(context)
        {
        }

        #region Software button Back
        public new void OnClick(Android.Views.View v)
        {
            // retrieve the current xamarin forms page instance
            var currentPage = Xamarin.Forms.Application.Current.MainPage.Navigation.NavigationStack.LastOrDefault();

            // check if the page has subscribed to 
            // the custom back button event
            if (currentPage != null &&
                currentPage.GetType().IsSubclassOf(typeof(DmMobile.Controls.ContentPage)) &&
                ((DmMobile.Controls.ContentPage)currentPage).CustomBackButtonAction != null)
            {
                // invoke the Custom back button action
                ((DmMobile.Controls.ContentPage)currentPage).CustomBackButtonAction.Invoke();
                // and disable the default back button action
            }
            else if (currentPage != null &&
                currentPage.GetType().IsSubclassOf(typeof(DmMobile.Controls.TabbedPage)) &&
                ((DmMobile.Controls.TabbedPage)currentPage).CustomBackButtonAction != null)
            {
                // invoke the Custom back button action
                ((DmMobile.Controls.TabbedPage)currentPage).CustomBackButtonAction.Invoke();
                // and disable the default back button action
            }
            else
            {
                Element?.PopAsync();
            }
        }
        #endregion
    }
}

```

**Comment by GeertvanHorrik** [comment] 2019-02-22 09:10
So what should be done to fix this in Catel in a solid manner? Interested in doing a PR?

**Comment by GreenKn1ght** [comment] 2019-02-22 10:00
[Here](https://github.com/GreenKn1ght/Catel.Xamarin.Forms.Todo/blob/master/src/Catel.Xamarin.Forms.Todo/ContentPage.cs) is my current implementation of ContentPage — lifecycle of the view model same as the view's lifecycle. But I still need to test it on UWP and iOS.

**Comment by GeertvanHorrik** [comment] 2019-02-26 10:15
@GreenKn1ght nice, interested in doing a PR once this has been tested on UWP / iOS?

**Comment by GreenKn1ght** [comment] 2019-02-26 14:56
Yeap.

**Comment by GeertvanHorrik** [comment] 2019-03-27 08:37
@GreenKn1ght is this something we can pick up for 5.10 or is it too complex?

**Comment by GreenKn1ght** [comment] 2019-03-27 08:39
I'm still testing the fix.

**Comment by GreenKn1ght** [comment] 2019-03-27 08:42
Now stuck on UWP - ViewModelLocator can't resolve VM. I'll try to figure it out on my own.

**Comment by GeertvanHorrik** [comment] 2019-03-27 08:51
UWP is my area of expertise ;-) If you upload / update an example, I can work on some fixes.

**Comment by GreenKn1ght** [comment] 2019-03-27 10:19
Updated the [sample](https://github.com/GreenKn1ght/Catel.Xamarin.Forms.Todo).
Android works, UWP throws NotSupportedException from UserControlLogic.

**Comment by GeertvanHorrik** [comment] 2019-03-27 10:38
Getting this:

```
'Method 'get_Item' in type 'Catel.Xamarin.Forms.Todo.ViewModels.TodoListViewModel' from assembly 'Catel.Xamarin.Forms.Todo, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.'
```

Maybe something with the limited reflection possibilities on UWP. Let me double check it all.

**Comment by GeertvanHorrik** [comment] 2019-03-27 10:59
It even happens on empty view models.

**Comment by GeertvanHorrik** [comment] 2019-03-27 12:16
Been stripping out stuff 1 by 1 from ViewModelBase, looks like whenever I remove the `IRelationalViewModel` interface, it starts working.

**Comment by GeertvanHorrik** [comment] 2019-03-27 12:22
I suspect this could be caused by IDataErrorInfo (defined for UWP in Catel), but then ValidatingModelBase should not work either (and that works just fine).

**Comment by GeertvanHorrik** [comment] 2019-03-27 12:31
Yep, that's it.

**Comment by GeertvanHorrik** [comment] 2019-03-27 12:33
So the .net standard uses IDataErrorInfo from the .net standard 2.0 implementation, and UWP uses the self-defined one (which obviously doesn't work).

**Comment by GeertvanHorrik** [comment] 2019-03-27 12:35
Maybe we can do type forwarding in https://docs.microsoft.com/en-us/dotnet/framework/app-domains/type-forwarding-in-the-common-language-runtime, but I don't want to lose Windows Phone (windows 10 mobile) support on UAP (use this myself) so updating to the min version of UAP that implements .net standard is not an option.

**Comment by GeertvanHorrik** [comment] 2019-03-27 12:36
Now I think of it, this might be caused because Catel.Core doesn't explicitly use the .net standard 2.0 implementation, but the platform-specific one (that is also included there). Maybe we can force it to use the .net standard one instead.

**Comment by GreenKn1ght** [comment] 2019-03-27 18:07
Can we support two versions of UAP? Since the Xamarin.Forms common library implements .NETStandard, we can't use the old version of UAP here anyway.

**Comment by GreenKn1ght** [comment] 2019-03-27 18:23
AFAIK, XF 3+ doesn't support WM10. Thus, we can only support it as a non-XF library

**Comment by GeertvanHorrik** [comment] 2019-03-27 18:30
The issue here is Catel.Core, that supports any platform (and the UWP version picks the UAP, not the .net standard implementation).

**Comment by GreenKn1ght** [comment] 2019-03-27 18:54
I understood that. I propose to target Catel.Core to uap10.0 (will use local types) and uap10.0.16299 (will use .NETStandard2.0 types). That should solve the problem, isn't it?

**Comment by GeertvanHorrik** [comment] 2019-03-27 18:55
Might work, let me try that.

**Comment by GeertvanHorrik** [comment] 2019-03-27 18:59
![image](https://user-images.githubusercontent.com/1246444/55104545-de050e80-50ca-11e9-817d-e3b762282c6e.png)

**Comment by GeertvanHorrik** [comment] 2019-03-27 19:12
Just pushed the first bits, need to leave now, but will try to build it on the build server.

**Comment by GeertvanHorrik** [comment] 2019-03-27 21:49
Build - 5.10.0-beta.15

![image](https://user-images.githubusercontent.com/1246444/55114573-98544000-50e2-11e9-86db-4e6af224816c.png)

**Comment by GreenKn1ght** [comment] 2019-03-27 22:49
It works!

**Comment by GeertvanHorrik** [comment] 2019-03-28 07:43
Awesome, thanks for pointing me in the right direction, it was a brilliant idea. You got sufficient stuff working to complete this ticket?

**Comment by GreenKn1ght** [comment] 2019-03-28 08:41
At first glance, yes. I still need to set up the environment for iOS. I will try to finish ticket at this weekend.

**Comment by GeertvanHorrik** [comment] 2019-03-28 08:47
Do you mind if we put this ticket for 5.11? Then we can close the beta and release 5.10 early next week.

**Comment by GreenKn1ght** [comment] 2019-03-28 09:36
Yes, let's put it for 5.11.

**Comment by GeertvanHorrik** [comment] 2019-06-07 12:08
@GreenKn1ght any updates?

**Comment by GeertvanHorrik** [comment] 2022-10-15 07:35
Since we removed support for all frameworks exception .NET 6 (WPF) for 6.0, I am closing this issue.

**Closed by GeertvanHorrik** 2022-10-15 07:35 UTC
Labels: bug, help wanted, planned
