### ISSUE TITLE
Problems with UWP and LogListeners

### ISSUE THREAD

**Issue by byrialsen** [Catel/Catel#1118] opened 2017-08-31 13:58 UTC
Hi @GeertvanHorrik. We already discussed this briefly in a private mail, but just so you don't forget it.

### Steps to reproduce
I add the following lines to my ModuleInitializer code 

```csharp
var logListener = new ConsoleLogListener();
LogManager.IgnoreCatelLogging = true;
LogManager.IsDebugEnabled = true;
LogManager.AddListener(logListener);
LogManager.AddDebugListener();
```

Platform: UWP
.NET version: 10393 (Anniversary update)
Catel: 5.1.0

### Actual behaviour

No logging appears in either LogListeners. If I check the `LogMessage` event, I can see the log text correctly in the `LogMessageEventArgs` but in the Visual Studio Output windows doesn't show anything

**Comment by GeertvanHorrik** [comment] 2017-09-09 18:24
Thanks for reporting. This is caused by the DebugLogListener using Debug.WriteLine. This call is removed from the assembly during release compilation (so it only makes sense to copy it into your own project).

We will investigate whether we can use Trace.WriteLine instead.

**Comment by GeertvanHorrik** [comment] 2017-09-14 18:33
I double checked, there is no real way to solve this. So closing this as won't fix, you'll need to copy the debugloglistener and use Debug.WriteLine in your own codebase.

**Closed by GeertvanHorrik** 2017-09-14 18:33 UTC
Labels: improvement, wont-fix
