### ISSUE TITLE
Application based on Catel 5.0 crashes if build with VS 2013 

### ISSUE THREAD

**Issue by szogun1987** [Catel/Catel#1072] opened 2017-07-20 13:45 UTC
### Steps to reproduce

1. Create new WPF project with Visual studio 2013
2. Install Catel.Core and Catel.MVVM
3. Put following code to main window constructor 
```
var command = new Command(() => { }, () => true);
```
4. Run app
Platform:
.NET version: 4.5

### Expected behaviour
Application crashes with stack:
```
System.ArgumentException: Cannot bind to the target method because its signature or security transparency is not compatible with that of the delegate type.
   at System.Delegate.CreateDelegate(Type type, Object firstArgument, MethodInfo method, Boolean throwOnBindFailure)
   at System.Delegate.CreateDelegate(Type type, Object firstArgument, MethodInfo method)
   at Catel.Reflection.DelegateHelper.CreateDelegate(Type delegateType, Object target, MethodInfo methodInfo)
   at Catel.Reflection.DelegateHelper.CreateDelegate(Type delegateType, MethodInfo methodInfo)
   at Catel.WeakFunc`1..ctor(Object target, Func`1 func)
   at Catel.MVVM.Command`2.InitializeActions(Action`1 executeWithParameter, Action executeWithoutParameter, Func`2 canExecuteWithParameter, Func`1 canExecuteWithoutParameter)
```
### Actual behaviour
Application shouldn't crash

### Workaround
Pass reference to instance method or null as second parameter

**Comment by GeertvanHorrik** [comment] 2017-07-20 16:32
What version of Catel unstable? I believe I fixed this last week.

**Comment by GeertvanHorrik** [comment] 2017-07-20 16:32
Or it could be the WeakFunc that has the same issue as WeakEvenListener (which is fixed now).

**Comment by szogun1987** [comment] 2017-07-20 16:34
Yes. I have used unstable version, that was available on Nuget when I've reported this issue

**Comment by GeertvanHorrik** [comment] 2017-07-20 16:35
Trying to reproduce now.

**Comment by GeertvanHorrik** [comment] 2017-07-20 16:39
Can't repro on VS2017 with .NET 4.5. What is the max .NET version you have installed on your dev machine (maybe it's an issue that needs fixing by updating the actual runtime)?

**Comment by szogun1987** [comment] 2017-07-20 16:40
Issue occurs only if I build with devtools used by VS 2013 (it is used by our build server) and doesn't occur if I use VS 2015

**Comment by GeertvanHorrik** [comment] 2017-07-20 16:52
To be fair 2013 is 2 versions ago. I think we can only support 2015 (and I'd rather drop this one as well) and 2017. Is it possible to build the project is msbuild (SDK only) instead of VS?

**Comment by szogun1987** [comment] 2017-07-20 16:58
VS 13 is a mind shortcut. We are using MS Build that is used by VS 2013. Solution contains couple cpp projects. Currently we are able to build it with VS 2013 and 2015, but version built with 2015 never have been sent on full regression tests. Currently build fails on VS 2017.

**Comment by GeertvanHorrik** [comment] 2017-07-24 09:42
So were you able to build with 2015?

**Comment by szogun1987** [comment] 2017-07-24 10:37
I'm able to build but app behavior haven't been checked by tests team for now.

**Comment by GeertvanHorrik** [comment] 2017-07-24 11:07
I would recommend that the test teams check it out since this is a major release. We are currently testing this against several of our products and haven't any issues yet.

I'll close this ticket because in all honesty we don't want to support systems that are being deprecated anyway (we simply don't have the resources to support this for others while we don't need it).

**Closed by GeertvanHorrik** 2017-07-24 11:07 UTC
