### ISSUE TITLE
ViewModelBase cannot be constructed on different thread: "The calling thread can not access this object because the object is owned by another thread"

### ISSUE THREAD

**Issue by gofrogi** [Catel/Catel#1385] opened 2019-08-02 15:39 UTC
Since Catel 5.10 it is not possible anymore to do this:

//code from MainWindowViewModel
...
await Task.Run(() =>Worker.DoIt();
...

// the class Worker.DoIt have this line of code
...
var x = new TaskNotificationViewModel();
...

Platform:
.NET version: 4.7.1

### Expected behaviour

the object of TaskNotificationViewModel should be created

### Actual behaviour
Exception thrown: 'System.InvalidOperationException' in WindowsBase.dll, 
The calling thread can not access this object because the object is owned by another thread

**Comment by GeertvanHorrik** [comment] 2019-08-06 09:11
Can you provide a small repro? We might have introduced a UI-thread aware element in the ViewModelBase, but could also be dependency injection?

**Comment by GeertvanHorrik** [comment] 2019-08-06 12:51
The only thing that makes sense to me would be `CatelEnvironment.GetIsInDesignMode()`. Can you call this method (results are cached) before constructing any view models:

```
DesignTimeHelper.InitializeDesignTime();
```

**Comment by gofrogi** [comment] 2019-08-06 14:18
i did it as asked but without success. I will prepare a repro.

**Comment by gofrogi** [comment] 2019-08-06 14:20
i did as ask but without success. I will prepare a repro.

**Comment by gofrogi** [comment] 2019-08-07 10:47
Hello, i created a small repro to reproduce my problem.
Just start the App with F5 and click the test button.
The app was created with VS2017 and old project template.
I tried it with VS2019 and new version of project template, but it seams something wrong with that template. I couldn't create a project. I get always an error from VS: "one o more errors occurred"

[WPFApplicationRepro_1385.zip](https://github.com/Catel/Catel/files/3476601/WPFApplicationRepro_1385.zip)

**Comment by GeertvanHorrik** [comment] 2019-08-07 10:50
> I tried it with VS2019 and new version of project template, but it seams something wrong with that template. I couldn't create a project. I get always an error from VS: "one o more errors occurred"

Please create a separate ticket for this in the Catel.Analyzers repository.

**Comment by GeertvanHorrik** [comment] 2019-08-07 11:04
Looks like it's caused by the AuditingHelper. Will add a fix in the current hotfix branch 5.11.1

**Comment by GeertvanHorrik** [comment] 2019-08-07 11:13
Probably caused by SubscribeKeyboardEventsOnViewModelCreationAuditor. Will dispatcher that call using IDispatcherService.

**Comment by gofrogi** [comment] 2019-08-07 11:40
but if you dispatch the call, you will loose the responsiveness of the UI.

**Comment by GeertvanHorrik** [comment] 2019-08-07 12:16
not really, it's just to subscribe to keyboard commands (and should be done whenever the view model is attached to the view). Please try the latest beta on nuget.

**Comment by GeertvanHorrik** [comment] 2019-08-07 12:16
if keyboards are already subscribed, it will immediately return the method anyway.

**Comment by GeertvanHorrik** [comment] 2019-08-07 12:22
btw vm construction should be super fast, why would you want to do this on a background thread anyway? If you have expensive initialization code, you should use `Task InitializeAsync` instead.

**Comment by gofrogi** [comment] 2019-08-07 12:39
in real case a have a light weight UserControl for showing progress. If the expensive process starts, an object of this ViewModel will be created and embedded in the main view. If i create that ViewModel before Task.Run, i would not have this problem. Anyway before 5.10 that was never a problem. If it couldn't fixed, i have to consider other strategy.

**Comment by GeertvanHorrik** [comment] 2019-08-07 12:39
it's fixed in the beta ;-)

**Comment by gofrogi** [comment] 2019-08-07 12:50
Wow! That was really super fast 👍 . Thank you Geert! You are great as always :)

**Closed** 2019-08-07 12:57 UTC
Labels: bug, need-repro
